#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac


SPLASH_BIN=/sbin/splash


if [ ! -x $SPLASH_BIN ]
then
	echo "$SPLASH_BIN not found. Bootsplash image won't be installed"
	exit 0
fi

SPLASH_FILE=/etc/untangle-bootsplash/config/bootsplash-1024x768.cfg

if [ ! -e $SPLASH_FILE ]
then
	echo "Config file $SPLASH_FILE not found. Bootsplash image won't be installed"
	exit 0
fi

$SPLASH_BIN -s -f $SPLASH_FILE > $DESTDIR/bootsplash
