FROM untangleinc/ngfw:base
LABEL maintainer="Sebastien Delafond <sdelafond@gmail.com>"

RUN apt-get update
RUN apt-get install --yes build-essential
RUN apt-get install --yes debhelper
RUN apt-get install --yes g++
RUN apt-get install --yes cmake
RUN apt-get install --yes libstdc++-6-dev

ENV SRC=/opt/untangle/classd
RUN mkdir -p ${SRC}
VOLUME ${SRC}

WORKDIR ${SRC}

CMD mkdir -p build_docker && cd build_docker && cmake .. && make && make install
