#! /bin/sh

mkdir -p /home/rbot/.ssh
chmod 700 /home/rbot/.ssh
chown -R rbot /home/rbot

RBOT_CONF_FILE=/home/rbot/.rbot/conf.yaml

perl -npe 's/\+NAME\+/rup//' $RBOT_CONF_FILE.template >| $RBOT_CONF_FILE

/etc/init.d/untangle-irc-bot restart

exit 0
