#!/bin/dash

echo "[`date`] Updating the ARP Eater."

## Reload the arp eater when the network info changes.
ARP_EATER_CONFIG_FILE=/etc/untangle-arp-eater.conf

if [ -f /etc/default/untangle-arp-eater ]; then
    . /etc/default/untangle-arp-eater
fi

/usr/share/untangle-arp-eater/bin/set_config ${ARP_EATER_CONFIG_FILE}

true