#!/bin/dash

echo "[DEBUG: `date`] Updating the ARP Eater."

## Reload the arp eater when the network info changes.
ARP_EATER_CONFIG_FILE=/etc/untangle-arp-eater.conf

if [ -f /etc/default/untangle-arp-eater ]; then
    . /etc/default/untangle-arp-eater
fi

mkdir -p /var/log/untangle-net-alpaca
/usr/share/untangle-arp-eater/bin/set_config ${ARP_EATER_CONFIG_FILE} >> /var/log/untangle-net-alpaca/dhcp.log 2>&1

true
