#!/bin/dash

echo "[DEBUG: `date`] Updating the ARP Eater."

## Reload the arp eater when the network info changes.
ARP_EATER_CONFIG_FILE=/etc/untangle-arp-eater.conf

ARP_EATER_BIND_PORT=3002

ARP_EATER_UTIL=/usr/share/untangle-arp-eater/bin/run_command.rb

if [ -f /etc/default/untangle-arp-eater ]; then
    . /etc/default/untangle-arp-eater
fi

if [ -x "${ARP_EATER_UTIL}" ]; then
    mkdir -p /var/log/untangle-net-alpaca
    ${ARP_EATER_UTIL} --port ${ARP_EATER_BIND_PORT}  refresh_system_state >> /var/log/untangle-net-alpaca/dhcp.log 2>&1
else
    echo "[WARN: `date`] Unable to run ${ARP_EATER_UTIL}."
fi

true
