#!/bin/dash
## Copyright (c) 2003-2008 Untangle, Inc.
##  All rights reserved.
## 
##  This software is the confidential and proprietary information of
##  Untangle, Inc. ("Confidential Information"). You shall
##  not disclose such Confidential Information.
## 
##  $Id: ADConnectorImpl.java 15443 2008-03-24 22:53:16Z amread $
## 

update_guest_address()
{
    local t_external_interface
    local t_address
    
    type VBoxControl > /dev/null 2>&1 || return
    
    ## Determine the external interface
    ## First use try the default gateway.
    t_external_interface=`ip route show | awk '/^default/ { print $5 ; exit 0 }'`
    
    ## Next try the interfaces.properties file.
    [ -z "${t_external_interface}" ] && [ -f /etc/untangle-net-alpaca/interface.properties ] && {
        t_external_interface=`sed  -e '/^com.untangle.interface-order/!d' -e 's|^.*External:\([^:]*\):\?.*$|\1|' /etc/untangle-net-alpaca/interface.properties`
        
        [ -z "${t_external_interface}" ] && return
        
        [ -L "/sys/class/net/${t_external_interface}/brport/bridge" ] && {
            t_external_interface=$( basename `readlink /sys/class/net/eth0/brport/bridge` )
        }
    }
    
    if [ -n "${t_external_interface}" ]; then
        t_address=`ip -f inet addr show ${t_external_interface} 2>|/dev/null | awk '/inet/ { sub( /\/.*$/, "", $2 ) ; print $2 ; exit 0  }'`
    else
        t_address=""
    fi

    VBoxControl -nologo guestproperty set /Untangle/Network/address "${t_address}"
}

## Run this script regardless of whether or not the UVM is running.
update_guest_address
