#!/bin/dash

FAILD_DEFAULTS_SCRIPT=${FAILD_DEFAULTS_SCRIPT:-/etc/default/untangle-faild}

## Update the environment
if [ -f ${FAILD_DEFAULTS_SCRIPT} ]; then
    . ${FAILD_DEFAULTS_SCRIPT}
fi

FAILD_LINK_STATUS_DIR=${FAILD_LINK_STATUS_DIR:-/etc/untangle-faild/link-status.d}

run-parts --lsbsysinit ${FAILD_LINK_STATUS_DIR}

exit 0

