#!/bin/dash -x

## This script requires elevated sudo privileges.
if [ -x /usr/share/untangle-faild/bin/set-uplink ] ; then
    sudo /usr/share/untangle-faild/bin/set-uplink
else
    echo "Missing the script  /usr/share/untangle-faild/bin/set-uplink"
fi


