#! /bin/bash

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

rsync -aH /usr/share/untangle-support-agent/rbot-home/ /home/rbot/

chmod 700 /home/rbot/.ssh
chown -R rbot /home/rbot

RBOT_CONF_FILE=/home/rbot/.rbot/conf.yaml

source /etc/default/untangle-vm

REMOTE_SUPPORT_ENABLE_URL_TEMPLATE="https://supportsys.untangle.com/cgi-bin/enable-remote-support.rb?license_key=%s&internal_ip=%s"
curl --silent --insecure --fail -o /dev/null `printf ${REMOTE_SUPPORT_ENABLE_URL_TEMPLATE} $(cat ${UID_FILE}) $(/usr/share/untangle/bin/ut-ip)`

if [[ -f $UID_FILE ]] ; then
  #UID_ID=`perl -npe 's/-//g' ${UID_FILE}`
  UID_ID=`cat ${UID_FILE}`
  CHANNEL="#untangle"
  if [[ $UID_ID = "012747a7bbff0752" || $UID_ID = "0000000000000000" || $UID_ID = "0127-47a7-bbff-0752" || $UID_ID = "0000-0000-0000-0000" ]] ; then
    UID_ID=`hostname | perl -npe 's/\..*//'`
    CHANNEL="#untangle-dev"
  else # IRC nicks can't start with a digit
    UID_ID=r$UID_ID
  fi
else
  UID_ID=`hostname`
  CHANNEL="#untangle-dev"
fi

perl -npe 's/\+NAME\+/'"$UID_ID"'/ ; s/\+CHANNEL\+/'"$CHANNEL"'/' $RBOT_CONF_FILE.template >| $RBOT_CONF_FILE

if pidof /usr/sbin/sshd > /dev/null ; then
  ourInit untangle-support-agent stop
  ourInit untangle-support-agent start
fi

exit 0
