#! /bin/bash

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

mkdir -p /home/rbot/.ssh
chmod 700 /home/rbot/.ssh
chown -R rbot /home/rbot

RBOT_CONF_FILE=/home/rbot/.rbot/conf.yaml

source /etc/default/untangle-vm

# FIXME: repeat ?
curl --silent --insecure --fail -o /dev/null `printf ${REMOTE_SUPPORT_ENABLE_URL_TEMPLATE} $(cat ${ACTIVATION_KEY_FILE}) $(/usr/share/untangle/bin/utip)`

if [[ -f $ACTIVATION_KEY_FILE ]] ; then
  KEY=`perl -npe 's/-//g' ${ACTIVATION_KEY_FILE}`
  CHANNEL="#untangle"
  if [[ $KEY = 012747a7bbff0752 || $KEY = 0000000000000000 ]] ; then
    KEY=`hostname | perl -npe 's/\..*//'`
    CHANNEL="#untangle-dev"
  else # IRC nicks can't start with a digit
    KEY=r$KEY
  fi
else
  KEY=`hostname`
  CHANNEL="#untangle-dev"
fi

perl -npe 's/\+NAME\+/'"$KEY"'/ ; s/\+CHANNEL\+/'"$CHANNEL"'/' $RBOT_CONF_FILE.template >| $RBOT_CONF_FILE

if pidof /usr/sbin/sshd > /dev/null ; then
  ourInit untangle-support-agent stop
  ourInit untangle-support-agent start
fi

exit 0
